//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioFreeZerg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainScreen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainScreen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioFreeZerg.MainScreen", typeof(MainScreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FindStationsCancelText {
            get {
                return ResourceManager.GetString("FindStationsCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string FindStationsConfirmationText {
            get {
                return ResourceManager.GetString("FindStationsConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter title keywords or station ID.
        /// </summary>
        internal static string FindStationsPromptText {
            get {
                return ResourceManager.GetString("FindStationsPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindStationsText {
            get {
                return ResourceManager.GetString("FindStationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio stations (double click or Enter to play).
        /// </summary>
        internal static string MainScreenTitleText {
            get {
                return ResourceManager.GetString("MainScreenTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextItemsText {
            get {
                return ResourceManager.GetString("NextItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No next items.
        /// </summary>
        internal static string NoNextItemsText {
            get {
                return ResourceManager.GetString("NoNextItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous items.
        /// </summary>
        internal static string NoPreviousItemsText {
            get {
                return ResourceManager.GetString("NoPreviousItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing.
        /// </summary>
        internal static string NowPlayingNothingText {
            get {
                return ResourceManager.GetString("NowPlayingNothingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; at {1}.
        /// </summary>
        internal static string NowPlayingSongText {
            get {
                return ResourceManager.GetString("NowPlayingSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown song at {0}.
        /// </summary>
        internal static string NowPlayingUnknownText {
            get {
                return ResourceManager.GetString("NowPlayingUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string PlayRandomStationText {
            get {
                return ResourceManager.GetString("PlayRandomStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PrevItemsText {
            get {
                return ResourceManager.GetString("PrevItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitAppText {
            get {
                return ResourceManager.GetString("QuitAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string ToggleCurrentStationText {
            get {
                return ResourceManager.GetString("ToggleCurrentStationText", resourceCulture);
            }
        }
    }
}
